Fix setting maxSize on initial ASG creation (#51)
This avoids an error where we were setting the default maxSize to 2,
causing:

ValidationError: Max bound, 2, must be greater than or equal to min
bound, 4

This happens if the minSize in the `.stack/deploy.yaml` file is set to a
value larger than `2`.