Harden AWS credential acquisition
We non-deterministically (and rarely) see errors like:

```
Synth command: bun /usr/src/app/cli.js --config .stack/deploy.yml _cdktf-synth
Error:         non-zero exit code 1

Command output on stderr:

    39 |       tryNextLink = options;
    40 |     } else if (options != null && typeof options === "object") {
    41 |       logger = options.logger;
    42 |       tryNextLink = options.tryNextLink ?? true;
    43 |     }
    44 |     super(message);
             ^
    CredentialsProviderError: Could not load credentials from any providers
          at new ProviderError (/usr/src/node_modules/@smithy/property-provider/dist-cjs/index.js:44:5)
          at new CredentialsProviderError (/usr/src/node_modules/@smithy/property-provider/dist-cjs/index.js:67:5)
          at /usr/src/node_modules/@aws-sdk/credential-provider-node/dist-es/defaultProvider.js:56:11
          at /usr/src/node_modules/@aws-sdk/credential-provider-node/dist-es/defaultProvider.js:60:2
          at /usr/src/node_modules/@smithy/property-provider/dist-cjs/index.js:99:33
```

Harden our credentials provider implementation to retry so that we are
more resilient to strange issues on the AWS side.